### ISSUE TITLE
validation error

### ISSUE THREAD

**Issue by tksohishi** [ikisuke/wagumi-sbt#13]
`node main.js create` 時に以下のvalidation error

```
@notionhq/client warn: request fail {
  code: 'validation_error',
  message: 'Could not find property with name or id: publish'
}
create metadata failed APIResponseError: Could not find property with name or id: publish
    at buildRequestError (/Users/takeshi/Work/wagumi-sbt/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/Users/takeshi/Work/wagumi-sbt/node_modules/@notionhq/client/build/src/Client.js:342:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.createMetadata (/Users/takeshi/Work/wagumi-sbt/src/lib/metadataCreate.js:229:17)
    at async /Users/takeshi/Work/wagumi-sbt/main.js:56:7 {
  code: 'validation_error',
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'set-cookie': [Array],
      'content-security-policy': [Array],
      'x-dns-prefetch-control': [Array],
      'x-frame-options': [Array],
      'strict-transport-security': [Array],
      'x-download-options': [Array],
      'x-content-type-options': [Array],
      'x-permitted-cross-domain-policies': [Array],
      'referrer-policy': [Array],
      'x-xss-protection': [Array],
      etag: [Array],
      vary: [Array],
      'cf-cache-status': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: '{"object":"error","status":400,"code":"validation_error","message":"Could not find property with name or id: publish"}'
}
```

**Comment by tksohishi** [comment]
@ikisuke これ直りました？

**Comment by ikisuke** [comment]
@tksohishi すいません、こちら修正いたしました！

**Comment by ikisuke** [comment]
ご確認次第、こちらのissueを閉じます！

**Comment by tksohishi** [comment]
確認しました！
